target : main.c add_disease.c find_disease.c find_BMI.c find_Hospital.c find_medicine.c find_reason.c health.h
	gcc  main.c add_disease.c find_disease.c find_BMI.c find_Hospital.c find_medicine.c find_reason.c -o a

run: target
	./a